version: '3.8'
services:
  price_db:
    image: postgres:latest
    container_name: price_scraper_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5433"
    volumes:
      - price_scraper_data:/var/lib/postgresql/data

volumes:
  price_scraper_data: